FROM postgres:17.4

RUN apt update && apt upgrade -y && rm -rf /var/lib/apt/lists/*

COPY pruebaCSV.csv /docker-entrypoint-initdb.d/
COPY init.sql /docker-entrypoint-initdb.d/

# Exponer el puerto por defecto
EXPOSE 5432
